### PR TITLE
Update architect-orb to 2.1.0

### PR DESCRIPTION
**Pull request by ubergesundheit**
Update architect-orb to 2.1.0 which will use giantswarm.github.io as catalog base url.

Towards giantswarm/giantswarm#15898

### CODE REVIEW

**Comment by ubergesundheit** [comment]
hello good people @kubasobon @tomahawk28

can you assist me in getting this PR merged? Seems your code depends on `k8s.io/kubernetes@v1.13.0` which has some vulnerabilities. Failing check is https://app.circleci.com/pipelines/github/giantswarm/app-checker/238/workflows/8d839687-b4b6-4e46-b9a7-ae6ee81f3751/jobs/912/parallel-runs/0/steps/0-117

I'm unsure how to upgrade.

**Comment by ubergesundheit** [comment]
ping @kubasobon @tomahawk28

**Comment by tomahawk28** [comment]
Hi, @ubergesundheit let me take a look. I will do that in another PR.

**Comment by ubergesundheit** [comment]
Very nice, thank you!

**Pull request merged**
